<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width = device-width, user-scalable=no,
      initial-scale = 1.0, maximum-scale = 1.0, minimum-scale = 0.5">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <title>Admin</title>

  <script type="text/javascript" src="../../public/js/jQuery.js"></script>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script src="//ajax.aspnetcdn.com/ajax/jquery.ui/1.10.3/jquery-ui.min.js"></script>

  <link href="../../public/css/global.css" rel="stylesheet" type="text/css"/>

</head>
<body>