<div id="main_forms">
  <div>
   <h2>Control Courses</h2>
   <h3>Add Course</h3>
   <form method="post">
      <input type="text" name="addCTitle" placeholder="Title"><br>
      <input type="text" name="addCTeacher" placeholder="Teacher"><br>
      <input type="submit" name="okCourse" value="OK"><br>
   </form>
   <h3>Change Course</h3>
   <form method="post">
      <input type="checkbox" id="selectCol0" name="changeCColumn" value="title">
      <label for="selectCol0">Change Title</label><br>
      <input type="checkbox" id="selectCol1" name="changeCColumn" value="teacher">
      <label for="selectCol1">Change Teacher</label><br>

      <input type="text" name="changeCTitle" placeholder="Title of Course"><br>
      <input type="text" name="changeCValue" placeholder="New value"><br>
      <input type="submit" name="okCourse" value="OK"><br>
   </form>
   <h3>Delete Course</h3>
   <form method="post">
      <input type="text" name="delC" placeholder="Title of Course"><br>
      <input type="submit" name="okCourse" value="OK"><br>
   </form>
  </div>
  <div>
   <h2>Control Students</h2>
   <h3>Add Student</h3>
   <form method="post">
      <input type="text" name="addSSurname" placeholder="Surname"><br>
      <input type="text" name="addSName" placeholder="Name"><br>
      <input type="mail" name="addSEmail" placeholder="Email"><br>
      <input type="text" name="addSTitlePhoto" placeholder="Title Photo"><br>
      <input type="submit" name="okStudent" value="OK"><br>
   </form>
   <h3>Change Student</h3>
   <form method="post">
      <input type="checkbox" id="selectSol0" name="changeSColumn" value="surname">
      <label for="selectCol0">Change Surname</label><br>
      <input type="checkbox" id="selectSol1" name="changeSColumn" value="name">
      <label for="selectCol1">Change Name</label><br>
      <input type="checkbox" id="selectCol2" name="changeSColumn" value="email">
      <label for="selectCol2">Change Email</label><br>
      <input type="checkbox" id="selectCol3" name="changeSColumn" value="index_photo">
      <label for="selectCol3">Change Title Photo</label><br>

      <input type="text" name="changeSId" placeholder="Id of Student"><br>
      <input type="text" name="changeSValue" placeholder="New value"><br>
      <input type="submit" name="okStudent" value="OK"><br>
   </form>
   <h3>Delete Student</h3>
   <form method="post">
      <input type="text" name="delS" placeholder="Id of Student"><br>
      <input type="submit" name="okStudent" value="OK"><br>
   </form>
  </div>
  <div>
   <h2>Control Students Course</h2>
   <h3>Add Student to Course</h3>
   <form method="post">
      <input type="text" name="addSidToC" placeholder="Student ID"><br>
      <input type="text" name="addStoCid" placeholder="Id of Course"><br>
      <input type="submit" name="okStudentCourse" value="OK"><br>
   </form>
   <h3>Delete Student from Course</h3>
   <form method="post">
      <input type="text" name="delSidFromC" placeholder="Student ID"><br>
      <input type="text" name="delSFromCid" placeholder="Id of Course"><br>
      <input type="submit" name="okStudentCourse" value="OK"><br>
   </form> 
  </div>
</div>