<?php
require __DIR__."/../../vendor/autoload.php"; //require autoloader

use Task\App\Controller\Admin\AdminUsersController;
use Task\App\Controller\Admin\AdminController;

session_start();

if (isset($_SESSION['login']) && isset($_SESSION['password'])){

    $admin = new AdminUsersController();

    $arrayValues = $admin -> checkAdmin($_SESSION['login'], $_SESSION['password']);

    if ($arrayValues[0] === true && $arrayValues[1] === true) {

            $block = new AdminController();

            //require head
            require __DIR__."/../../public/html/admin_head.phtml"; 

            echo "<a href='../../login.php' id='exit'>EXIT</a>";

            //require admin buttons to change table
            require __DIR__."/adminhtml/templates/admin_button_tables.phtml"; 

        if (isset($_POST['arrInfoAdd'])) {
       	   $block -> checkInfoToAdd($_SESSION['Table'],
       	   	                        $_POST['arrInfoAdd'][0],
       	   	                        $_POST['arrInfoAdd'][1]);

        }

        if (isset($_POST['arrToChange'])) {
        	
        	$block -> checkInfoToChange($_SESSION['Table'],
        		                        $_POST['arrToChange'][0],
        		                        $_POST['arrToChange'][1],
        		                        $_POST['arrToChange'][2]);

        }

        if (isset($_POST['selectElemDel'])) {
        	
        	$block -> checkInfoToDel($_SESSION['Table'],
        		                        $_POST['selectElemDel']);

        }

        if (isset($_POST['exit'])) {
        	 unset($_SESSION['login']);
           unset($_SESSION['password']);
        }    

        if (isset($_POST['titleTabel'])) {

            $_SESSION['Table'] = $_POST['titleTabel'];

            $tableInfo = $block -> getInfo($_POST['titleTabel']); 
            //show inputs add to tables
            echo "<div id='mainAdminInfo'>";
            echo "<div id='divValuesToAdd'>";
            foreach ($tableInfo[0] as $array_keys_inputs => $value_inputs) { 

           	   if (!is_numeric($array_keys_inputs)) {

                    if ($array_keys_inputs !== 'id') {
                      
                       $nameColumn = $array_keys_inputs;

                        //require admin_add
                       require __DIR__."/adminhtml/templates/admin_add_values.phtml";
                    } 
           	   }    
            }

            echo "<input type='button' class='add_values' value='Add'>";
            echo "</div>";
            echo "<table>
	                <tr>";

            foreach ($tableInfo[0] as $array_keys => $array_names) {

           	   if (!is_numeric($array_keys)) {

           	      	echo "<th>$array_keys </th>";

           	   }    

            }

            echo "<th>x</th>";
            echo" </tr>";

            $table_values = array_values($tableInfo);
        
            foreach ($table_values as $keys => $values) {

                echo "<tr>";

                foreach ($values as $key => $value) {

           	       if (!is_numeric($key)) {

                      if ($key === 'id'){ 
                    	 $idField = $value;
                      }

                      $selectColumn = $key;

           	      	  require __DIR__."/adminhtml/templates/admin_inputs_tochange.phtml"; 

           	        }
           	            
                }
                echo "<td class='deleteField' data-id-remove='".$idField."'>x</td>";
                echo "</tr>";

            }     
      
            echo "</table>";
            echo "</div>";
    
        } //end of table

       require __DIR__."/../../public/html/admin_foot.phtml"; //require admin_foot
    }else{
  	    header('location: ../../login.php');
    }
}else{
	header('location: ../../login.php');
}
?>