<?php 
require __DIR__."/../../public/html/headMain.phtml"; //require tag head

require __DIR__."/../../vendor/autoload.php"; //require autoloader

use Task\App\Controller\News\News;

$block = new News();

if (isset($_POST['arrToRender'])) {  //select actual render buttons

    $partMin = $_POST['arrToRender'][0];
    $actualButtonsNumber = $_POST['arrToRender'][1];

    if ($actualButtonsNumber >= 3) {
    		$pointBefore = $actualButtonsNumber - 1;
    	    $actualButtonsNumber += 1;
    }else{
         	$actualButtonsNumber = 2;
            $pointBefore = $actualButtonsNumber - 1;
            $actualButtonsNumber += 1;
    }
}else{

   $partMin = 0;
   $actualButtonsNumber = 2;
   $pointBefore = $actualButtonsNumber - 1;
   $actualButtonsNumber += 1;

}


$short_info = $block -> getShortInfo($partMin); //get array block news

$countBlocks = 0;

foreach ($short_info as $key => $value) {

  $countBlocks++;

  if ($countBlocks <= 5) {

	foreach ($value as $keyValue => $item) {

		switch ($keyValue) {
			case 0:
				$id = $item;
				break;
			case 1:
				$title = $item;
				break;
			case 2:
				$short_descriptions = $item;
				break;
			case 4:
				$publication_date = $item;
				break;
			
		}
		
	}

	require __DIR__."/frontend/templates/home_short_descriptions.phtml"; //require template with div news

   }else{

   	    break;
   
   }
}

$count_elems = $block -> countElems();

$number_list = 0;

require __DIR__."/frontend/templates/back_tostart_button.phtml"; 

    for ($i=0; $i <= $count_elems; $i++) { // buttons to render list news

	      if ($i % 5 === 0) {

              $number_list++;
      
              if ($number_list >= $pointBefore && $number_list <= $actualButtonsNumber) {

                  $min = $i;

	              //rquire buttons to change list news

                  require __DIR__."/frontend/templates/render_list_buttons.phtml"; 

               }

	       }
    }

$endButton = $number_list;
$end = $count_elems - 1;

require __DIR__."/frontend/templates/back_toend_button.phtml"; 


require __DIR__."/../../public/html/foot.phtml"; //require footer html
?>